# Generated by Django 5.1.1 on 2024-10-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('well_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annual_oil_production', models.IntegerField()),
                ('annual_gas_production', models.IntegerField()),
                ('annual_brine_production', models.IntegerField()),
                ('well_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.wellnumber')),
            ],
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='api_well_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.wellnumber'),
        ),
    ]
